site_name: Tatin User Guide
repo_url: https://github.com/aplteam/Tatin
repo_name: aplteam/Tatin

docs_dir: source

nav:
  - Home:
    - About Tatin: index.md
    - Load and update strategy: load-and-update-strategy.md
    - Glossary: glossary.md
    - Release notes: release-notes.md
    - Previous version: 'https://tatin.dev/v1/documentation'
  - Use:
    - Get started: get-started.md
    - User commands: user-commands.md
    - API functions: api.md
    - Settings: user-settings.md
    - Older versions: older-versions.md
  - Publish:
    - About publishing: about-publishing.md
    - Publish packages: publish-packages.md
    - User commands: user-commands-publish.md
    - Package configuration: package-configuration.md
    - (Public interface): public-interface.md
  - Host:
    - About hosting: about-hosting.md
    - (Credentials): server-credentials.md
    - (Install the server): installingthetatinserver.md
    - (Server tips and tricks): server-tipsandtricks.md
    - (Run Dyalog behind Apache): rundyalogbehindapache.md
    - (Usage data): usagedata.md
  - Contribute:
    - (Tatin for contributors): tatinforcontributors.md
    - (Github): github.md

theme:
  custom_dir: overrides
  favicon: 'img/favicon.ico'
  logo:  'img/tatin-logo.svg'
  icon:
    logo:  'img/tatin-logo.svg'
  name: material
  font:
      text: Be Vietnam Pro
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
  palette:
    primary: custom
    accent: custom

extra:
  version_maj: 0
  version_majmin: 0.112
  # version:
  #   provider: mike

extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # - privacy
  - search
  - git-revision-date
  # - macros
  # - monorepo
  # - caption:
  #     table:
  #       enable: true
  #       start_index: 1
  #       increment_index: 1
  #       position: bottom

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      title: On this page

