site_name: Tatin User Guide
repo_url: https://github.com/aplteam/Tatin
repo_name: aplteam/Tatin

docs_dir: source

nav:
  - Revised:
    - About Tatin: index.md
    - Get started: get-started.md
    - User commands: user-commands.md
    - Caching: caching.md
    - Github: github.md
    - Installing the client: installingandupdatingthetatinclient.md
    - Installing the server: installingthetatinserver.md
    - Package configuration: packageconfiguration.md
    - Publishing packages: publishingpackages.md
    - Run Dyalog behind Apache: rundyalogbehindapache.md
    - Semantic versioning: semanticversioning.md
    - Server tips and tricks: server-tipsandtricks.md
    - Syntax reference: syntaxreference.md
    - Tatin and OneDrive: tatinandonedrive.md
    - Tatin for contributors: tatinforcontributors.md
    - Load and update strategy: tatinsloadandupdatestrategy.md
    - User settings: tatinusersettings.md
    - Usage data: usagedata.md
    - Release notes: release-notes.md
  - Original:
    - Home: original/_readme.md
    - Caching: original/caching.md
    - First steps: original/firststepswithtatin.md
    - Github: original/github.md
    - Installing the client: original/installingandupdatingthetatinclient.md
    - Installing the server: original/installingthetatinserver.md
    - Introduction: original/introduction.md
    - Package configuration: original/packageconfiguration.md
    - Publishing packages: original/publishingpackages.md
    - Release notes: original/releasenotes.md
    - Run Dyalog behind Apache: original/rundyalogbehindapache.md
    - Semantic versioning: original/semanticversioning.md
    - Server tips and tricks: original/server-tipsandtricks.md
    - Syntax reference: original/syntaxreference.md
    - Tatin and OneDrive: original/tatinandonedrive.md
    - Tatin for contributors: original/tatinforcontributors.md
    - Load and update strategy: original/tatinsloadandupdatestrategy.md
    - User settings: original/tatinusersettings.md
    - Usage data: original/usagedata.md

theme:
  custom_dir: overrides
  favicon: 'img/favicon.ico'
  logo:  'img/tatin-logo.svg'
  icon:
    logo:  'img/tatin-logo.svg'
  name: material
  font:
      text: Be Vietnam Pro
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
  palette:
    primary: custom
    accent: custom

extra:
  version_maj: 0
  version_majmin: 0.112
  # version:
  #   provider: mike

extra_css:
  - style/main.css
  - style/extra.css
  - style/admonition-ucmdhelp.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  # - privacy
  - search
  - git-revision-date
  # - macros
  # - monorepo
  # - caption:
  #     table:
  #       enable: true
  #       start_index: 1
  #       increment_index: 1
  #       position: bottom

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      title: On this page

